// frontend/vue/src/presentation/pages/ProfilePage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { applySignedOut, bootstrapSession, user } from "../../application/session";
import AppButton from "../components/AppButton.vue";
import AppIcon from "../components/AppIcon.vue";

const { t } = useI18n();
const router = useRouter();
const ready = ref(false);

const isGuest = computed(() => !user.value || user.value.guest || !user.value.email);
const avatarInitial = computed(() => (user.value?.email?.[0] ?? "?").toUpperCase());

onMounted(async () => {
  await bootstrapSession();
  ready.value = true;
  if (isGuest.value) await router.replace("/login");
});

async function logout() {
  await applySignedOut();
  await router.push("/");
}
</script>

<template>
  <article
    v-if="ready && !isGuest && user"
    class="auth-card mx-auto space-y-4"
    data-testid="profile-page"
  >
    <div class="flex items-center gap-3">
      <span class="profile-avatar profile-avatar-lg">{{ avatarInitial }}</span>
      <h1 class="font-display text-2xl font-semibold">
        {{ t("profile.title") }}
      </h1>
    </div>
    <dl class="grid grid-cols-2 gap-2 text-sm">
      <dt class="text-muted-foreground">
        {{ t("profile.email") }}
      </dt>
      <dd data-testid="profile-email">
        {{ user.email }}
      </dd>
      <dt class="text-muted-foreground">
        {{ t("profile.id") }}
      </dt>
      <dd data-testid="profile-id">
        {{ user.id }}
      </dd>
    </dl>
    <AppButton
      variant="outline"
      data-testid="auth-logout"
      @click="logout"
    >
      <AppIcon name="logout" />
      {{ t("nav.logout") }}
    </AppButton>
  </article>
</template>

// frontend/react/src/presentation/pages/ProfilePage.tsx
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import type { User } from "@/shared";
import { AppButton } from "../components/AppButton";
import { AppIcon } from "../components/AppIcon";

export function ProfilePage({
  user,
  ready,
  onLogout,
}: {
  user: User | null;
  ready: boolean;
  onLogout: () => Promise<void>;
}) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const isGuest = !user || user.guest || !user.email;

  useEffect(() => {
    if (ready && isGuest) navigate("/login", { replace: true });
  }, [ready, isGuest, navigate]);

  if (!ready || isGuest || !user) return null;

  return (
    <article className="auth-card mx-auto space-y-4" data-testid="profile-page">
      <div className="flex items-center gap-3">
        <span className="profile-avatar profile-avatar-lg">{user.email[0].toUpperCase()}</span>
        <h1 className="font-display text-2xl font-semibold">{t("profile.title")}</h1>
      </div>
      <dl className="grid grid-cols-2 gap-2 text-sm">
        <dt className="text-muted-foreground">{t("profile.email")}</dt>
        <dd data-testid="profile-email">{user.email}</dd>
        <dt className="text-muted-foreground">{t("profile.id")}</dt>
        <dd data-testid="profile-id">{user.id}</dd>
      </dl>
      <AppButton variant="outline" data-testid="auth-logout" onClick={() => void onLogout()}>
        <AppIcon name="logout" />
        {t("nav.logout")}
      </AppButton>
    </article>
  );
}
