// frontend/nuxt/app/pages/profile.vue
<script setup lang="ts">
const { t } = useI18n();
const { user, bootstrap, applySignedOut } = useSession();
const localePath = useLocalePath();
const ready = ref(false);

const isGuest = computed(() => !user.value || user.value.guest || !user.value.email);
const avatarInitial = computed(() => (user.value?.email?.[0] ?? "?").toUpperCase());

onMounted(async () => {
  await bootstrap();
  ready.value = true;
  if (isGuest.value) await navigateTo(localePath("/login"), { replace: true });
});

async function logout() {
  await applySignedOut();
  await navigateTo(localePath("/"));
}
</script>

<template>
  <article
    v-if="ready && !isGuest && user"
    class="auth-card mx-auto space-y-4"
    data-testid="profile-page"
  >
    <div class="flex items-center gap-3">
      <span class="profile-avatar profile-avatar-lg">{{ avatarInitial }}</span>
      <h1 class="font-display text-2xl font-semibold">
        {{ t("profile.title") }}
      </h1>
    </div>
    <dl class="grid grid-cols-2 gap-2 text-sm">
      <dt class="text-muted-foreground">
        {{ t("profile.email") }}
      </dt>
      <dd data-testid="profile-email">
        {{ user.email }}
      </dd>
      <dt class="text-muted-foreground">
        {{ t("profile.id") }}
      </dt>
      <dd data-testid="profile-id">
        {{ user.id }}
      </dd>
    </dl>
    <AppButton
      variant="outline"
      data-testid="auth-logout"
      @click="logout"
    >
      <AppIcon name="logout" />
      {{ t("nav.logout") }}
    </AppButton>
  </article>
</template>

// frontend/next/app/profile/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslation } from "react-i18next";
import { applySignedOut, authApi } from "@/src/application/session";
import { useSession } from "@/src/presentation/components/SessionProvider";
import { AppButton } from "@/src/presentation/components/AppButton";
import { AppIcon } from "@/src/presentation/components/AppIcon";

export default function ProfilePage() {
  const { t } = useTranslation();
  const router = useRouter();
  const { user, setUser, setChat } = useSession();
  const [ready, setReady] = useState(false);
  const isGuest = !user || user.guest || !user.email;

  useEffect(() => {
    void (async () => {
      const me = await authApi.me();
      setUser(me);
      setReady(true);
      if (!me || me.guest || !me.email) router.replace("/login");
    })();
  }, [router, setUser]);

  async function logout() {
    await applySignedOut(
      (next) => setUser(next),
      (next) => setChat(next),
    );
    router.push("/");
  }

  if (!ready || isGuest || !user) return null;

  return (
    <article className="auth-card mx-auto space-y-4" data-testid="profile-page">
      <div className="flex items-center gap-3">
        <span className="profile-avatar profile-avatar-lg">{user.email[0].toUpperCase()}</span>
        <h1 className="font-display text-2xl font-semibold">{t("profile.title")}</h1>
      </div>
      <dl className="grid grid-cols-2 gap-2 text-sm">
        <dt className="text-muted-foreground">{t("profile.email")}</dt>
        <dd data-testid="profile-email">{user.email}</dd>
        <dt className="text-muted-foreground">{t("profile.id")}</dt>
        <dd data-testid="profile-id">{user.id}</dd>
      </dl>
      <AppButton variant="outline" data-testid="auth-logout" onClick={() => void logout()}>
        <AppIcon name="logout" />
        {t("nav.logout")}
      </AppButton>
    </article>
  );
}
