// frontend/nuxt/app/components/ChatPanel.vue
<script setup lang="ts">
const { t } = useI18n();
const { chat, chatApi, user } = useSession();
const draft = ref("");
const loadingOlder = ref(false);
const showGuestNotice = computed(
  () => Boolean(user.value && (user.value.guest || !user.value.email)),
);

async function send() {
  const text = draft.value;
  draft.value = "";
  await chatApi.send(chat.value, text, (next) => {
    chat.value = next;
  });
}

async function retry() {
  await chatApi.retry(chat.value, (next) => {
    chat.value = next;
  });
}

async function loadOlder() {
  if (loadingOlder.value) return;
  loadingOlder.value = true;
  try {
    await chatApi.loadOlder(chat.value, (next) => {
      chat.value = next;
    });
  } finally {
    loadingOlder.value = false;
  }
}
</script>

<template>
  <section class="chat-shell">
    <p
      v-if="showGuestNotice"
      class="guest-notice"
      data-testid="guest-banner"
    >
      {{ t("auth.guestBanner") }}
    </p>
    <ChatMessageList
      :messages="chat.messages ?? []"
      :pending="Boolean(chat.pending)"
      :has-more="Boolean(chat.hasMore)"
      :loading-older="loadingOlder"
      @retry="retry"
      @load-older="loadOlder"
    />
    <ChatComposer
      v-model="draft"
      :pending="chat.pending"
      @send="send"
    />
  </section>
</template>

// frontend/next/src/presentation/components/ChatPanel.tsx
"use client";

import { useState } from "react";
import { useTranslation } from "react-i18next";
import { chatApi } from "@/src/application/session";
import { useSession } from "./SessionProvider";
import { ChatComposer } from "./ChatComposer";
import { ChatMessageList } from "./ChatMessageList";

export function ChatPanel() {
  const { t } = useTranslation();
  const { chat, setChat, user } = useSession();
  const [draft, setDraft] = useState("");
  const [loadingOlder, setLoadingOlder] = useState(false);
  const showGuestNotice = Boolean(user && (user.guest || !user.email));

  async function send() {
    const text = draft;
    setDraft("");
    await chatApi.send(chat, text, setChat);
  }

  async function loadOlder() {
    if (loadingOlder) return;
    setLoadingOlder(true);
    try {
      await chatApi.loadOlder(chat, setChat);
    } finally {
      setLoadingOlder(false);
    }
  }

  return (
    <section className="chat-shell">
      {showGuestNotice ? (
        <p className="guest-notice" data-testid="guest-banner">
          {t("auth.guestBanner")}
        </p>
      ) : null}
      <ChatMessageList
        messages={chat.messages}
        pending={chat.pending}
        hasMore={chat.hasMore}
        loadingOlder={loadingOlder}
        onRetry={() => void chatApi.retry(chat, setChat)}
        onLoadOlder={() => void loadOlder()}
      />
      <ChatComposer draft={draft} pending={chat.pending} onDraft={setDraft} onSend={() => void send()} />
    </section>
  );
}
