// frontend/next/src/presentation/components/AppButton.tsx
"use client";

import type { ButtonHTMLAttributes, ReactNode } from "react";

const variants = {
  primary: "btn-primary",
  outline: "btn-outline",
  ghost: "btn-ghost",
  icon: "btn-icon",
} as const;

export function AppButton({
  variant = "primary",
  className = "",
  children,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: keyof typeof variants;
  children: ReactNode;
}) {
  return (
    <button className={`btn ${variants[variant]} ${className}`} {...props}>
      {children}
    </button>
  );
}

// frontend/nuxt/app/components/AppButton.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    variant?: "primary" | "outline" | "ghost" | "icon";
    type?: "button" | "submit";
    disabled?: boolean;
  }>(),
  { variant: "primary", type: "button", disabled: false },
);
</script>

<template>
  <button
    :type="type"
    class="btn"
    :class="{
      'btn-primary': variant === 'primary',
      'btn-outline': variant === 'outline',
      'btn-ghost': variant === 'ghost',
      'btn-icon': variant === 'icon',
    }"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>
