// frontend/nuxt/app/components/LocaleToggle.vue
<script setup lang="ts">
const { t, locale, setLocale } = useI18n();
const localeCookie = useCookie<"id" | "en">("locale", {
  default: () => "id",
  sameSite: "lax",
});

onMounted(() => {
  if (localeCookie.value && localeCookie.value !== locale.value) {
    void setLocale(localeCookie.value);
  }
});

async function choose(next: "id" | "en") {
  if (locale.value === next) return;
  await setLocale(next);
  localeCookie.value = next;
}
</script>

<template>
  <div
    class="seg-toggle"
    role="group"
    :aria-label="t('nav.language')"
    data-testid="lang-switch"
  >
    <button
      type="button"
      :class="{ 'is-active': locale === 'id' }"
      :aria-pressed="locale === 'id'"
      @click="choose('id')"
    >
      ID
    </button>
    <button
      type="button"
      :class="{ 'is-active': locale === 'en' }"
      :aria-pressed="locale === 'en'"
      @click="choose('en')"
    >
      EN
    </button>
  </div>
</template>

// frontend/react/src/presentation/components/LocaleToggle.tsx
import { useTranslation } from "react-i18next";

export function LocaleToggle() {
  const { t, i18n } = useTranslation();
  const isId = i18n.language.startsWith("id");

  function choose(next: "id" | "en") {
    void i18n.changeLanguage(next);
    localStorage.setItem("locale", next);
  }

  return (
    <div className="seg-toggle" role="group" aria-label={t("nav.language")} data-testid="lang-switch">
      <button type="button" className={isId ? "is-active" : ""} aria-pressed={isId} onClick={() => choose("id")}>
        ID
      </button>
      <button type="button" className={!isId ? "is-active" : ""} aria-pressed={!isId} onClick={() => choose("en")}>
        EN
      </button>
    </div>
  );
}
