// frontend/next/src/presentation/components/ChatAssistantResponse.tsx
"use client";

import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { parseAssistantContent } from "@/src/shared/domain/parseReasoning";

export function ChatAssistantResponse({
  content,
  streaming,
}: {
  content: string;
  streaming?: boolean;
}) {
  const { t } = useTranslation();
  const parsed = useMemo(() => parseAssistantContent(content), [content]);
  const thinkingText = parsed.thinking.trim();
  const responseText = parsed.response;
  const showResponse = Boolean(responseText.trim());
  const showThinkingIndicator =
    Boolean(streaming) && !showResponse && parsed.phase !== "responding";
  const showThinkingText = showThinkingIndicator && Boolean(thinkingText);

  return (
    <div className="chat-assistant-response" data-testid="chat-assistant-response">
      {showThinkingIndicator ? (
        <div className="chat-reasoning" data-testid="chat-reasoning">
          <div className="chat-reasoning-head">
            <span className="chat-thinking-dots" aria-hidden="true">
              <span />
              <span />
              <span />
            </span>
            <span data-testid="chat-reasoning-label">{t("chat.thinking")}</span>
          </div>
          {showThinkingText ? (
            <div className="chat-reasoning-text" data-testid="chat-reasoning-text">
              {thinkingText}
            </div>
          ) : null}
        </div>
      ) : null}
      {showResponse ? (
        <div className="chat-response-text" data-testid="chat-response-text">
          {responseText}
          {streaming ? <span className="chat-cursor" aria-hidden="true" /> : null}
        </div>
      ) : null}
    </div>
  );
}

// frontend/vue/src/presentation/components/ChatAssistantResponse.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { parseAssistantContent } from "@/shared/domain/parseReasoning";

const props = defineProps<{ content: string; streaming?: boolean }>();
const { t } = useI18n();

const parsed = computed(() => parseAssistantContent(props.content));
const thinkingText = computed(() => parsed.value.thinking.trim());
const responseText = computed(() => parsed.value.response);
const showResponse = computed(() => Boolean(responseText.value.trim()));
const showThinkingIndicator = computed(
  () => props.streaming && !showResponse.value && parsed.value.phase !== "responding",
);
const showThinkingText = computed(
  () => showThinkingIndicator.value && Boolean(thinkingText.value),
);
</script>

<template>
  <div
    class="chat-assistant-response"
    data-testid="chat-assistant-response"
  >
    <div
      v-if="showThinkingIndicator"
      class="chat-reasoning"
      data-testid="chat-reasoning"
    >
      <div class="chat-reasoning-head">
        <span
          class="chat-thinking-dots"
          aria-hidden="true"
        >
          <span /><span /><span />
        </span>
        <span data-testid="chat-reasoning-label">{{ t("chat.thinking") }}</span>
      </div>
      <div
        v-if="showThinkingText"
        class="chat-reasoning-text"
        data-testid="chat-reasoning-text"
      >
        {{ thinkingText }}
      </div>
    </div>
    <div
      v-if="showResponse"
      class="chat-response-text"
      data-testid="chat-response-text"
    >
      {{ responseText }}<span
        v-if="streaming"
        class="chat-cursor"
        aria-hidden="true"
      />
    </div>
  </div>
</template>
